config/routes.rb
Kvitter::Application.routes.draw do

  root :to => "messages#index"

  get 'kvitter' => 'messages#index'

  get 'admin' => 'messages#admin'

  controller :sessions do
    get 'login' => :new
    post 'login' => :create
    get 'logout' => :destroy # TODO why delete 'logout'... in example
  end

  resources :users

  resources :messages

  # You can have the root of your site routed with "root"
  # just remember to delete public/index.html.
  # root :to => 'welcome#index'

  # See how all your routes lay out with "rake routes"
end

app/models/message.rb
class Message < ActiveRecord::Base

  validates :msg, presence: true

end

app/models/user.rb
require 'digest/sha2'

# see agile web development w/rails 4th, p.184ff
#
class User < ActiveRecord::Base

  validates :name, :presence => true, :uniqueness => true
  validates :password, :confirmation => true

  validate :password_must_be_present # TODO read up on this
  
  after_destroy :ensure_an_admin_remains

  def ensure_an_admin_remains
    if User.count.zero?
      raise "Can't delete last user"
    end
  end

  attr_accessor :password_confirmation # create reader, writer for pw_confirmation

  attr_reader :password
  def password=( password ) # non-standard writer, store encrypted pw instead
    @password = password
    
    if password.present?
      generate_salt
      self.hashed_password = self.class.encrypt_password( password, salt )
    end

  end    
  
  def User.authenticate( name, password )
    if user = find_by_name( name )  # lookup user in db
      if user.hashed_password == encrypt_password( password, user.salt )
        user #return value
      end
    end
  end

  def User.encrypt_password( password, salt)
    Digest::SHA2.hexdigest( password + "wibble" + salt ) # wibble?
  end  
  
  private
  
  # TODO this puts up validation error if no hashed_pw present/generated??
  def password_must_be_present
    errors.add( :password, "Missing password" ) unless hashed_password.present?
  end

  def generate_salt
    self.salt = self.object_id.to_s + rand.to_s
  end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_filter :authorise
  protect_from_forgery
  
  protected

    def authorise
      unless User.find_by_id( session[:user_id] )
        redirect_to login_url, notice: "Please log in"
      end
    end
  
end

app/controllers/messages_controller.rb
class MessagesController < ApplicationController

  skip_before_filter :authorise, :only => [:index, :new, :create] #login to admin (edit, delete, show)

  # GET /messages
  # GET /messages.json
  def index
    @messages = Message.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @messages }
    end
  end

  # GET /messages
  # GET /messages.json
  def admin
    @messages = Message.all

    respond_to do |format|
      format.html # admin.html.erb
      format.json { render json: @messages }
    end
  end

  # GET /messages/1
  # GET /messages/1.json
  def show
    @message = Message.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @message }
    end
  end

  # GET /messages/new
  # GET /messages/new.json
  def new
    @message = Message.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @message }
    end
  end

  # GET /messages/1/edit
  def edit
    @message = Message.find(params[:id])
  end

  # POST /messages
  # POST /messages.json
  def create
    @message = Message.new(params[:message])

    respond_to do |format|
      if @message.save
        format.html { redirect_to messages_url, notice: 'Message was successfully created.' }
        format.json { render json: @message, status: :created, location: @message }
      else
        format.html { render action: "new" }
        format.json { render json: @message.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /messages/1
  # PUT /messages/1.json
  def update
    @message = Message.find(params[:id])

    respond_to do |format|
      if @message.update_attributes(params[:message])
        format.html { redirect_to @message, notice: 'Message was successfully updated.' }
        format.json { head :ok }
      else
        format.html { render action: "edit" }
        format.json { render json: @message.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /messages/1
  # DELETE /messages/1.json
  def destroy
    @message = Message.find(params[:id])
    @message.destroy

    respond_to do |format|
      format.html { redirect_to admin_url }
      format.json { head :ok }
    end
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
 
  skip_before_filter :authorise

  def new
  end

  def create
    if user = User.authenticate( params[:name], params[:password])
      session[:user_id] = user.id
      #TODO redirect where?
      redirect_to root_url, alert: "Logged in"
    else
      redirect_to login_url, alert: "Invalid user/password combination"
    end
  end

  def destroy
    session[:user_id] = nil
    redirect_to login_url, alert: "Logged out"
  end

end

app/controllers/users_controller.rb
# see agile web development w/rails 4th, p.184ff
#
class UsersController < ApplicationController
  skip_before_filter :authorise, :only => [:new, :index, :create, :update] #need be logged in to destroy user
  
  
  # GET /users
  # GET /users.json
  def index
    @users = User.order( :name )

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @users }
    end
  end

  # GET /users/1
  # GET /users/1.json
  def show
    @user = User.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @user }
    end
  end

  # GET /users/new
  # GET /users/new.json
  def new
    @user = User.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @user }
    end
  end

  # GET /users/1/edit
  def edit
    @user = User.find(params[:id])
  end

  # POST /users
  # POST /users.json
  def create
    @user = User.new(params[:user])

    respond_to do |format|
      if @user.save
        format.html { redirect_to( users_url, notice: "User #{@user.name} was successfully created." ) }
      else
        format.html { render action: "new" }
      end
    end
  end

  # PUT /users/1
  # PUT /users/1.json
  def update
    @user = User.find(params[:id])

    respond_to do |format|
      if @user.update_attributes(params[:user])
        format.html { redirect_to( users_url, notice: "User #{@user.name} was successfully updated." ) }
      else
        format.html { render action: "edit" }
      end
    end
  end

  # DELETE /users/1
  # DELETE /users/1.json
  def destroy
    @user = User.find(params[:id])
    begin
      @user.destroy
      flash[:notice] = "User #{@user.name} deleted"
    rescue Exception => e
      flash[:notice] = e.message
    end
            
    respond_to do |format|
      format.html { redirect_to users_url }
      format.json { head :ok }
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/messages_helper.rb
module MessagesHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Kvitter</title>
  <%= stylesheet_link_tag    "application" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

app/views/messages/_form.html.erb
<%= form_for(@message) do |f| %>
  <% if @message.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@message.errors.count, "error") %> prohibited this message from being saved:</h2>

      <ul>
      <% @message.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.text_area :msg %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/messages/admin.html.erb
<h1>Administrera kvitter</h1>

<table>
  <tr>
    <th>Msg</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @messages.each do |message| %>
  <tr>
    <td><%= message.msg %></td>
    <td><%= link_to 'Show', message %></td>
    <td><%= link_to 'Destroy', message, confirm: 'Are you sure?', method: :delete %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'Nytt kvitter', new_message_path %>

app/views/messages/edit.html.erb
<h1>Editing message</h1>

<%= render 'form' %>

<%= link_to 'Show', @message %> |
<%= link_to 'Back', messages_path %>

app/views/messages/index.html.erb
<h1>Kvitter</h1>

<table>

<% @messages.each do |message| %>
  <tr>
    <td>><%= message.msg %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'Kvittra!', new_message_path %>

app/views/messages/new.html.erb
<h1>Kvittra!</h1>

<%= render 'form' %>

<%= link_to 'Back', messages_path %>

app/views/messages/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Msg:</b>
  <%= @message.msg %>
</p>


<%= link_to 'Edit', edit_message_path(@message) %> |
<%= link_to 'Back', messages_path %>

app/views/users/_form.html.erb
<%= form_for(@user) do |f| %>
  <% if @user.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@user.errors.count, "error") %> prohibited this user from being saved:</h2>

      <ul>
      <% @user.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <fieldset>
  <legend>Enter user details</legend>

  <div>
    <%= f.label :name %>
    <%= f.text_field :name %>
  </div>
  
  <div>
    <%= f.label :password, 'Password' %>
    <%= f.text_field :password %>
  </div>

  <div>
    <%= f.label :password_confirmation, 'Confirm password' %>
    <%= f.text_field :password_confirmation %>
  </div>

  <div class="actions">
    <%= f.submit %>
  </div>
  
  </fieldset>
<% end %>

app/views/users/edit.html.erb
<h1>Editing user</h1>

<%= render 'form' %>

<%= link_to 'Show', @user %> |
<%= link_to 'Back', users_path %>

app/views/users/index.html.erb
<h1>Listing users</h1>

<%if notice %>
  <p id="notice"><%= notice %></p>
<% end %>


<table>
  <tr>
    <th>Name</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @users.each do |user| %>
  <tr>
    <td><%= user.name %></td>
    <td><%= link_to 'Show', user %></td>
    <td><%= link_to 'Edit', edit_user_path(user) %></td>
    <td><%= link_to 'Destroy', user, confirm: 'Are you sure?', method: :delete %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New User', new_user_path %>

app/views/users/new.html.erb
<h1>New user</h1>

<%= render 'form' %>

<%= link_to 'Back', users_path %>

app/views/users/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Name:</b>
  <%= @user.name %>
</p>

<p>
  <b>Hashed password:</b>
  <%= @user.hashed_password %>
</p>

<p>
  <b>Salt:</b>
  <%= @user.salt %>
</p>


<%= link_to 'Edit', edit_user_path(@user) %> |
<%= link_to 'Back', users_path %>